/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HttpResponse {
  statusCode: number
  header: Record<string, string>
  data: Buffer
}
export interface HttpStreamResponse {
  statusCode: number
  header: Record<string, string>
  file: string
}
export declare function get(url: string, headers: Record<string, string>): Promise<HttpResponse>
export declare function post(url: string, headers: Record<string, string>, body?: Buffer | undefined | null): Promise<HttpResponse>
export declare function fetch(method: string, url: string, headers: Record<string, string>, body?: Buffer | undefined | null): Promise<HttpResponse>
export declare function stream(method: string, url: string, headers: Record<string, string>, filePath: string, body?: Buffer | undefined | null): Promise<HttpStreamResponse>
