/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RequestOptions {
  method?: string
  headers?: Record<string, string>
  body?: Buffer
  proxy?: string
}
export interface HttpResponse {
  statusCode: number
  headers: Record<string, string>
  data: Buffer
}
export interface HttpStreamResponse {
  statusCode: number
  headers: Record<string, string>
  file: string
}
export declare function get(url: string, options?: RequestOptions | undefined | null): Promise<HttpResponse>
export declare function post(url: string, options?: RequestOptions | undefined | null): Promise<HttpResponse>
export declare function fetch(url: string, options: RequestOptions): Promise<HttpResponse>
export declare function stream(url: string, filePath: string, options?: RequestOptions | undefined | null): Promise<HttpStreamResponse>


/* file: types.d.ts */


export interface HttpResponsePlus extends HttpResponse {
  json(): any
  text(): string
  buffer(): Buffer
}